const path = require("path")
console.log(path.dirname("C:/Users/Salony/Desktop/Nodejs_Celebal/path_module/index.js"))
console.log(path.basename("C:/Users/Salony/Desktop/Nodejs_Celebal/path_module/index.js"))
console.log(path.resolve())
console.log(path.parse("C:/Users/Salony/Desktop/Nodejs_Celebal/path_module/index.js"))